Feat header junior
leutamo/conectatech pull request #3
Opened 2022-01-21 06:53 UTC by JuniorAlmeyda

Agrega componente del Header para Usuario y Profesional

2022-01-21 13:57 UTC, carosalazar28 requested changes
Lo veo super! te dejé un par de comments nada más.

2022-01-21 13:57 UTC, carosalazar28 commented on src/pages/header/user/UserHeader.component.jsx
> +
Se te van recurrentemente dos espacios en los componentes

2022-01-21 13:57 UTC, carosalazar28 commented on src/pages/header/professional/ProfessionalHeader.component.jsx
> +
Dos espacios menos

2022-01-21 13:57 UTC, carosalazar28 commented on src/App.js
> +  const [professionaName, setProfessionalName] = useState('Profesional')
Para setear estos estados vas a consumir del API desde el componente de App?

Porque no dejar esto desde cada uno de los componentes?

2022-01-21 14:02 UTC, carosalazar28 commented
Les falta agregar las reglas para bloquear el rebase, les dejó una imagen para que lo hagan o lo revisen.

![image](https://user-images.githubusercontent.com/65572735/150539974-c12e1529-6560-4b88-b72f-e4e72283e964.png)

2022-01-22 00:39 UTC, JuniorAlmeyda commented on src/App.js
> +  const [professionaName, setProfessionalName] = useState('Profesional')
Como el sistema necesita un logueo, pensamos en capturar el nombre de la persona

2022-01-24 13:16 UTC, carosalazar28 approved these changes

2022-01-24 13:30 UTC, carosalazar28 commented on src/App.js
> +  const [professionaName, setProfessionalName] = useState('Profesional')
Listo, pero igual recuerda que también puede ser desde el componente ya que App se renderiza en todas las URL entonces si van a ejecutar un request desde este componente van a disminuir el performance por que van a lanzar request frecuentemente

2022-01-25 00:21 UTC, merged