Feat: agrega componente para el registro de tipo usuario y profesional
leutamo/conectatech pull request #5
Opened 2022-01-24 08:44 UTC by JuniorAlmeyda

2022-01-24 13:27 UTC, carosalazar28 requested changes

2022-01-24 13:27 UTC, carosalazar28 commented on src/pages/aside/AsideLogo.component.jsx
> +  }
Revisa todo el formateo y la identación

2022-01-24 13:27 UTC, carosalazar28 commented on src/pages/registro/Registro.component.jsx
> +          <input placeholder="Ingrese sus nombres" className="input input-bordered" type="text"></input>
El elemento input no necesita una etiqueta de cierre, dale una revisada a la documentación de [MDN](https://developer.mozilla.org/es/docs/Web/HTML/Element/input/text)

2022-01-24 13:27 UTC, carosalazar28 commented on src/pages/registro/Registro.component.jsx
> +		<div className="w-2/4">
De paso revisa acá esta identación

2022-01-24 13:27 UTC, carosalazar28 commented on src/pages/registro/profesional/RegistroProfesional.component.jsx
> +		<div className="w-2/4">
Acá lo mismo que en el anterior

2022-01-24 13:27 UTC, carosalazar28 commented on src/App.js
> +import Registro from './pages/registro/Registro.component'
Estos dos componentes los estás importando pero no la estas usando

2022-01-24 14:21 UTC, JuniorAlmeyda commented on src/pages/aside/AsideLogo.component.jsx
> +  }
Lo siento, por alguna razón en mi VS-Code se ve bien pero al momento de hacer el commit se ve con varios espacios, estoy tratando de solucionar ese tema pero sin éxito aún

2022-01-24 14:22 UTC, JuniorAlmeyda commented on src/pages/registro/Registro.component.jsx
> +          <input placeholder="Ingrese sus nombres" className="input input-bordered" type="text"></input>
Sí lo sé, pero por alguna razón cuando quiero levantar el proyecto sin poner etiqueta de cierre me sale error y me obliga a ponerlo

2022-01-24 15:11 UTC, carosalazar28 requested changes

2022-01-24 15:11 UTC, carosalazar28 commented on src/pages/aside/AsideLogo.component.jsx
> +	</aside>
Revisa de nuevo porque las etiquetas de cierre te quedan con más identación

2022-01-24 15:31 UTC, carosalazar28 approved these changes

2022-01-25 00:58 UTC, dcyar approved these changes

2022-01-25 00:59 UTC, merged